name: Linter

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  linter:
    name: Lint Code Base
    runs-on: ubuntu-latest
    permissions:
      statuses: write  # for github/super-linter/slim to mark status of each linter run

    steps:
      - name: Checkout Code
        uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3.5.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Lint Code Base
        uses: github/super-linter/slim@bb2d833b08b6c288608686672b93a8a4589cdc49 # v4.9.7

        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Markdown lint complains about the issue templates
          FILTER_REGEX_EXCLUDE: .github/ISSUE_TEMPLATE/*
          VALIDATE_YAML: false
